apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netpol-playwright-mcp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: PLACEHOLDER_REPO_URL
    path: argocd/base/resources/network-policies/playwright-mcp
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: playwright-mcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
