creation_rules:
  # Talos configuration files (local dev use only)
  - path_regex: talos/.*
    age: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
  # ArgoCD secrets
  - path_regex: argocd/.*secret.*\.yaml$
    age: age1m58w3a52776phxqzeyztezx09u4z7964ug0skf2rvzrzw63v2dhq602hcx
