# Claude Code UI HTTPRoute - routes through oauth2-proxy with Keycloak auth
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: claudecodeui-route
  namespace: claudecodeui
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: https
  hostnames:
    - claude.etcd.me
  rules:
    # Health check endpoint - bypasses oauth2-proxy
    - matches:
        - path:
            type: Exact
            value: /api/health
      backendRefs:
        - name: claudecodeui
          port: 3001
    # WebSocket connections for real-time updates
    - matches:
        - path:
            type: PathPrefix
            value: /socket.io
      backendRefs:
        - name: claudecodeui-oauth2-proxy
          port: 4180
    # SSO logout redirect
    - matches:
        - path:
            type: Exact
            value: /signout
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /oauth2/sign_out?rd=https%3A%2F%2Fauth.etcd.me%2Frealms%2Fhomelab%2Fprotocol%2Fopenid-connect%2Flogout%3Fclient_id%3Dclaudecodeui
            statusCode: 302
    # All other requests go to oauth2-proxy
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: claudecodeui-oauth2-proxy
          port: 4180
