apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-route
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  hostnames:
    - loki.cluster.local
  parentRefs:
    - name: main-gateway
      namespace: default
      sectionName: https
  rules:
    - backendRefs:
        - name: loki-stack-grafana
          port: 80
