apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-communication
  namespace: claudecodeui
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow oauth2-proxy to communicate with claudecodeui
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: claudecodeui
