apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 1  # Single instance for lab, increase for HA

  # PostgreSQL version
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4

  # Storage - using Longhorn for persistence
  storage:
    size: 5Gi
    storageClass: longhorn

  # Bootstrap with initial databases
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: postgres-credentials

  # Resource limits
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  # Secret postgres-credentials is defined in overlay secrets.sops.yaml
